# Generated by Django 6.0.6 on 2026-07-13 21:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='titulo',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data',
        ),
        migrations.AlterField(
            model_name='evento',
            name='fim',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2050, 12, 31))]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='inicio',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2050, 12, 31))]),
        ),
    ]
