# Generated by Django 6.0.6 on 2026-07-30 17:49

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_rename_titulo_evento_nome_remove_evento_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fim',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2000, 1, 1, 0, 0)), django.core.validators.MaxValueValidator(datetime.datetime(2050, 12, 31, 23, 59, 59))]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='inicio',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2000, 1, 1, 0, 0)), django.core.validators.MaxValueValidator(datetime.datetime(2050, 12, 31, 23, 59, 59))]),
        ),
    ]
