# Generated by Django 6.0.6 on 2026-07-10 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turmas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membrodeturma',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turma',
            name='usuarios',
            field=models.ManyToManyField(related_name='turmas', related_query_name='turma', through='turmas.MembroDeTurma', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membrodeturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.turma'),
        ),
        migrations.AddConstraint(
            model_name='membrodeturma',
            constraint=models.UniqueConstraint(fields=('usuario', 'turma'), name='unique_usuario_turma'),
        ),
    ]
