# Generated by Django 6.0.6 on 2026-07-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='codigo',
            field=models.CharField(default=None, max_length=6, unique=True),
        ),
    ]
