# Generated by Django 6.0.6 on 2026-07-10 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendarios', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendarios', related_query_name='calendario', to='turmas.turma'),
        ),
        migrations.AddField(
            model_name='membrodecalendario',
            name='calendario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarios.calendario'),
        ),
    ]
