# Generated by Django 6.0.6 on 2026-07-10 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendarios', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membrodecalendario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendario',
            name='usuarios',
            field=models.ManyToManyField(related_name='calendarios', related_query_name='calendario', through='calendarios.MembroDeCalendario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='membrodecalendario',
            constraint=models.UniqueConstraint(fields=('usuario', 'calendario'), name='unique_usuario_calendario'),
        ),
    ]
